consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  CreateUserPayload:
    example:
      name: Facere sed distinctio possimus doloribus vel at.
    properties:
      name:
        example: Facere sed distinctio possimus doloribus vel at.
        type: string
    required:
    - name
    title: CreateUserPayload
    type: object
  User:
    description: A user (default view)
    example:
      created_at: 1998-11-22T05:13:42+09:00
      href: /users/1
      id: 1
      name: test
    properties:
      created_at:
        description: Date of creation
        example: 1998-11-22T05:13:42+09:00
        format: date-time
        type: string
      href:
        description: API href of user
        example: /users/1
        type: string
      id:
        description: ID of user
        example: 1
        format: int64
        type: integer
      name:
        description: Name of account
        example: test
        type: string
    required:
    - id
    - href
    - name
    - created_at
    title: 'Mediatype identifier: application/vnd.user+json; view=default'
    type: object
  UserCollection:
    description: UserCollection is the media type for an array of User (default view)
    example:
    - created_at: 1998-11-22T05:13:42+09:00
      href: /users/1
      id: 1
      name: test
    items:
      $ref: '#/definitions/User'
    title: 'Mediatype identifier: application/vnd.user+json; type=collection; view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  description: Attendance management system
  title: Kintai
  version: ""
paths:
  /_ah/health:
    get:
      description: Perform health check.
      operationId: health#health
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: health health
      tags:
      - health
  /users:
    get:
      description: Retrive all users.
      operationId: User#list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UserCollection'
      schemes:
      - http
      summary: list User
      tags:
      - User
    post:
      description: Create new user
      operationId: User#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateUserPayload'
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to created resource
              pattern: /users/[0-9]+
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create User
      tags:
      - User
  /users/{userId}:
    get:
      description: Get user by id
      operationId: User#show
      parameters:
      - description: User ID
        in: path
        minimum: 1
        name: userId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show User
      tags:
      - User
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/User'
schemes:
- http
swagger: "2.0"
